import { google, youtube_v3 } from "googleapis";
import { fetchAllPages } from "@/helpers/pagination";
import { batchVideoRequests } from "@/helpers/batch";
import { retryWithBackoff } from "@/helpers/retry";
import { createOAuthClient } from "./oauth";
import type { YouTubeChannel, YouTubeVideo } from "./types";

const asBig = (v?: string | null): bigint => BigInt(v ?? "0");
export class YouTubeDataApi { private readonly youtube: youtube_v3.Youtube;
  constructor(accessToken: string) { const auth = createOAuthClient(); auth.setCredentials({ access_token: accessToken }); this.youtube = google.youtube({ version: "v3", auth }); }
  async getAuthenticatedChannel(): Promise<YouTubeChannel> { const res = await retryWithBackoff(() => this.youtube.channels.list({ part: ["snippet", "statistics", "contentDetails", "brandingSettings"], mine: true })); const item = res.data.items?.[0]; if (!item?.id) throw new Error("No authenticated YouTube channel found"); return { id: item.id, title: item.snippet?.title ?? "Untitled", description: item.snippet?.description ?? undefined, customUrl: item.snippet?.customUrl ?? undefined, publishedAt: item.snippet?.publishedAt ? new Date(item.snippet.publishedAt) : undefined, uploadsPlaylistId: item.contentDetails?.relatedPlaylists?.uploads ?? undefined, thumbnailUrl: item.snippet?.thumbnails?.high?.url ?? item.snippet?.thumbnails?.default?.url ?? undefined, country: item.snippet?.country ?? undefined, branding: item.brandingSettings ?? undefined, statistics: { viewCount: asBig(item.statistics?.viewCount), subscriberCount: asBig(item.statistics?.subscriberCount), hiddenSubscriberCount: item.statistics?.hiddenSubscriberCount ?? false, videoCount: asBig(item.statistics?.videoCount) } }; }
  async getUploadVideoIds(playlistId: string): Promise<string[]> { const items = await fetchAllPages((pageToken) => retryWithBackoff(async () => { const res = await this.youtube.playlistItems.list({ part: ["contentDetails"], playlistId, maxResults: 50, pageToken }); return { items: res.data.items ?? [], nextPageToken: res.data.nextPageToken }; })); return items.map((i) => i.contentDetails?.videoId).filter((id): id is string => Boolean(id)); }
  async getVideos(ids: readonly string[]): Promise<YouTubeVideo[]> { const batches = await Promise.all(batchVideoRequests(ids).map((idBatch) => retryWithBackoff(() => this.youtube.videos.list({ part: ["snippet", "statistics", "status", "contentDetails"], id: idBatch })))); return batches.flatMap((res) => res.data.items ?? []).map((item) => ({ id: item.id ?? "", title: item.snippet?.title ?? "Untitled", description: item.snippet?.description ?? undefined, publishedAt: item.snippet?.publishedAt ? new Date(item.snippet.publishedAt) : undefined, duration: item.contentDetails?.duration ?? undefined, definition: item.contentDetails?.definition ?? undefined, dimension: item.contentDetails?.dimension ?? undefined, caption: item.contentDetails?.caption === "true", licensedContent: item.contentDetails?.licensedContent ?? false, privacyStatus: item.status?.privacyStatus ?? undefined, uploadStatus: item.status?.uploadStatus ?? undefined, tags: item.snippet?.tags ?? [], thumbnails: item.snippet?.thumbnails ?? undefined, categoryId: item.snippet?.categoryId ?? undefined, statistics: { viewCount: asBig(item.statistics?.viewCount), likeCount: asBig(item.statistics?.likeCount), commentCount: asBig(item.statistics?.commentCount), favoriteCount: asBig(item.statistics?.favoriteCount) } })); }
}
